# Project information

site_name: AWS Core Services
site_description: 'In this workshop, you will host a Static Website and build 2-tier Application Architecture, covering the core services and best practices for Compute, Networking, Storage and Databases.'
#site_author: 'beralfon@amazon.com'
site_url: 'http://aws-core-services.xyz'

# Repository
#repo_name: 'aws-samples/aws-security-workshops'
repo_url: 'https://github.com/thecloudranger/aws-core-services-devance'

google_analytics: ['UA-1111111-2', 'aws-core-services.xyz']

extra:
  social: 
    - icon: fontawesome/brands/github-alt
      link: https://github.com/thecloudranger
    - icon: fontawesome/solid/home
      link: http://aws-core-services.xyz

nav:
    - Home: index.md
    - Identity & Access Management: getting-started-with-iam.md
    - Publish a Static WebSite: getting-started-with-amazon-s3.md
    - Two-tier Application (Linux): 
      - Getting Started with Amazon VPC: getting-started-with-amazon-vpc.md
      - Getting Started with Linux on Amazon EC2: getting-started-with-linux-on-amazon-ec2.md
      - Getting Started with Amazon RDS: getting-started-with-amazon-rds-new.md
    - Next.JS on AWS using Serverless Framework:
      - Overview: nextjs-serverless-overview.md
      - Getting Started: nextjs-serverless-getting-started.md
      - First Deployment: nextjs-serverless-first-deployment.md
      - Dynamic Routes: nextjs-serverless-dynamic-routes.md
    - Amplify on AWS: 
      - Overview: amplify-on-aws.md
      - Preparing your development environment: preparing-your-development-environment.md
      - Adding Authentication: adding-authentication.md
      - Adding Analytics: adding-analytics.md
      - Creating a GraphQL API: adding-api.md
      - Adding Storage: adding-storage.md
      - Add Translate Text and Text to Speech: adding-predictions.md
      - Adding Hosting: adding-hosting.md   

theme:
  name: material
  palette:
    primary: cyan
    accent: cyan
  icon:
    logo: fontawesome/brands/aws
    repo: fontawesome/brands/git-alt
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pyembed.markdown
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

